name: pub_cache_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  archive: ^3.6.1
  args: ^2.6.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  tar: ^2.0.0

dev_dependencies:
  very_good_analysis: ^6.0.0

executables:
  pub_cache_server:
